# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 46f4b5e45573305d9f9cc5d491e96b4737e9e71483e4f18515891cf019353589cfe3a64948f22c62c7ec04659aac8ef0daf32835abaea7303d70b3807882311e

test:
  secret_key_base: 8673babe48aec441a0e4917b2f07728ad014aa4dff3c108846647e6a1d2c11c2d50b73538d943498906a72d223944d6783fa3a2ac8b86e69a06166a7360550bd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
